### ISSUE TITLE
[Enhancement] Multiple reagents purchased form vendor

### ISSUE THREAD

**Issue by sWxJaPkT** [Lichery/Automaton#2]
I think a really neat feature of this addon is to automatically buy reagents from vendors for you

A good enhancement would be for you to buy multiple items from the list

Rune of Teleportation & Rune of Portals for example

**Comment by Artur91425** [comment]
What is the problem in the beginning to buy one item, and then another?
What you offer can only be done by creating a queue for the purchase of items, but this is too long to implement. It's easier to buy one item and then manually install the purchase of another item.
