### ISSUE TITLE
Sell function

### ISSUE THREAD

**Issue by sWxJaPkT** [Lichery/Automaton#3]
When I have lots of greys in my inventory the server disconnects me when I visit a merchant. I think it is because the addon is telling the client to do too many things at once. Not sure

**Comment by waytoomuchgaming** [comment]
I have that problem too, and i can confirm it's volume related. I don't know the exact amount of sells which made you disconnect, tho.

**Comment by Artur91425** [comment]
Added timer 0.01 sec for sale each items. This must fix this problem.
When you sell items, the game will freeze for a while selling all your trash.
Freezing time = 0.01*amount selling items [seconds]
